### ISSUE TITLE
RSSI without BLE connection

### ISSUE THREAD

**Issue by dneykov** [iDevicesInc/SweetBlue#229]
Hello,
I'm looking for a way to determinate distance using RSSI signal before I make BLE connection. My idea is as soon as I scan my device, continuously read advertising data for about a second to collect as much RSSI signals as possible and make calculations with them.
So I'm asking is it possible to read RSSI continuously with SeetBlue before I connect.
Thanks.

**Comment by ryanidev** [comment]
Yes it is possible. When a device is discovered from the native stack, the RSSI value gets updated. So, when you see a BleDevice get DISCOVERED, track the rssi in your app. Then it will show up as REDISCOVERED from then on, and you can get the RSSI the same way, knowing it has been updated since the last scan.

You're at the mercy of Android's Bluetooth stack here, so only waiting a second probably won't get you too many values. I've seen some devices take 3-5 seconds before even being seen once. In theory, the closer you are, the quicker it should get discovered, but again, I've seen this NOT happen before. You'll have to test a lot, with different phones to determine the best amount of time to wait.
